import {
  Briefcase,
  FileText,
  Printer,
  Paperclip,
  Calculator,
  Mail,
  Clipboard,
  ClipboardList,
  Folder,
  Archive,
  Inbox,
  Send,
  BookOpen,
  GraduationCap,
  NotebookPen,
  Pencil,
  Search,
  Book,
  BookMarked,
  Library,
  Highlighter,
  PenTool,
  Compass,
  Anchor,
  LifeBuoy,
  HeartHandshake,
  Mic,
  Music,
  Users,
  Handshake,
  Sparkles,
  Home,
  Sofa,
  Utensils,
  Trash2,
  Lightbulb,
  Wrench,
  WashingMachine,
  DoorOpen,
  Armchair,
  Lamp,
  Key,
  Activity,
  Dumbbell,
  Salad,
  Pill,
  Bed,
  Droplet,
  Stethoscope,
  Thermometer,
  Moon,
  Wallet,
  PiggyBank,
  CreditCard,
  Receipt,
  TrendingUp,
  Banknote,
  Coins,
  ShoppingCart,
  ShoppingBag,
  Baby,
  Cake,
  Gift,
  PartyPopper,
  UsersRound,
  Smile,
  Shirt,
  Glasses,
  Crown,
  Award,
  Trees,
  Mountain,
  Sun,
  CloudRain,
  Bike,
  Footprints,
  Leaf,
  Flower,
  Sprout,
  Recycle,
  Laptop,
  Smartphone,
  Wifi,
  Camera,
  Headphones,
  Monitor,
  Tablet,
  Phone,
  Video,
  Battery,
  Car,
  Plane,
  TrainFront,
  Map,
  Luggage,
  Sailboat,
  Ship,
  Route,
  Ticket,
  Bus,
  ChefHat,
  Coffee,
  Apple,
  UtensilsCrossed,
  Cookie,
  Pizza,
  IceCreamCone,
  Milk,
  Carrot,
  Soup,
  Clock,
  Calendar,
  AlarmClock,
  Timer,
  Flag,
  Star,
  Bell,
  Target,
  ListChecks,
  CheckCheck,
  type LucideIcon,
} from 'lucide-react';
import type { TaskIconKey } from '@navis/shared';

/**
 * De la clave del catálogo (§7.1, D14) al componente de lucide que la pinta.
 * El icono es una clave de texto en la base de datos; quien lo resuelve es
 * cada plataforma, con su propia librería (Regla 7 §6).
 */
export const TASK_ICON_MAP: Record<TaskIconKey, LucideIcon> = {
  briefcase: Briefcase,
  'file-text': FileText,
  printer: Printer,
  paperclip: Paperclip,
  calculator: Calculator,
  mail: Mail,
  clipboard: Clipboard,
  'clipboard-list': ClipboardList,
  folder: Folder,
  archive: Archive,
  inbox: Inbox,
  send: Send,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'notebook-pen': NotebookPen,
  pencil: Pencil,
  search: Search,
  book: Book,
  'book-marked': BookMarked,
  library: Library,
  highlighter: Highlighter,
  'pen-tool': PenTool,
  compass: Compass,
  anchor: Anchor,
  'life-buoy': LifeBuoy,
  'heart-handshake': HeartHandshake,
  mic: Mic,
  music: Music,
  users: Users,
  handshake: Handshake,
  sparkles: Sparkles,
  home: Home,
  sofa: Sofa,
  utensils: Utensils,
  'trash-2': Trash2,
  lightbulb: Lightbulb,
  wrench: Wrench,
  'washing-machine': WashingMachine,
  'door-open': DoorOpen,
  armchair: Armchair,
  lamp: Lamp,
  key: Key,
  activity: Activity,
  dumbbell: Dumbbell,
  salad: Salad,
  pill: Pill,
  bed: Bed,
  droplet: Droplet,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  moon: Moon,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  receipt: Receipt,
  'trending-up': TrendingUp,
  banknote: Banknote,
  coins: Coins,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  baby: Baby,
  cake: Cake,
  gift: Gift,
  'party-popper': PartyPopper,
  'users-round': UsersRound,
  smile: Smile,
  shirt: Shirt,
  glasses: Glasses,
  crown: Crown,
  award: Award,
  trees: Trees,
  mountain: Mountain,
  sun: Sun,
  'cloud-rain': CloudRain,
  bike: Bike,
  footprints: Footprints,
  leaf: Leaf,
  flower: Flower,
  sprout: Sprout,
  recycle: Recycle,
  laptop: Laptop,
  smartphone: Smartphone,
  wifi: Wifi,
  camera: Camera,
  headphones: Headphones,
  monitor: Monitor,
  tablet: Tablet,
  phone: Phone,
  video: Video,
  battery: Battery,
  car: Car,
  plane: Plane,
  'train-front': TrainFront,
  map: Map,
  luggage: Luggage,
  sailboat: Sailboat,
  ship: Ship,
  route: Route,
  ticket: Ticket,
  bus: Bus,
  'chef-hat': ChefHat,
  coffee: Coffee,
  apple: Apple,
  'utensils-crossed': UtensilsCrossed,
  cookie: Cookie,
  pizza: Pizza,
  'ice-cream-cone': IceCreamCone,
  milk: Milk,
  carrot: Carrot,
  soup: Soup,
  clock: Clock,
  calendar: Calendar,
  'alarm-clock': AlarmClock,
  timer: Timer,
  flag: Flag,
  star: Star,
  bell: Bell,
  target: Target,
  'list-checks': ListChecks,
  'check-check': CheckCheck,
};

/** `book-open` → `bookOpen`: la clave de traducción de su etiqueta accesible. */
export function taskIconLabelKey(icon: string): string {
  return icon.replace(/-([a-z0-9])/g, (_match, letter: string) => letter.toUpperCase());
}
